workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
    - when: always

image: maven:3.8.1-openjdk-17

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"
  MVN_REPOSITORY: "-Dmaven.repo.local=.m2/repository"

stages:
  - compile
  - test
  - package
  - build
  - deploy

maven-compile:
  stage: compile
  script: "mvn ${MAVEN_CLI_OPTS} compile"

maven-test:
  stage: test
  needs:
    - maven-compile
  script: "mvn ${MAVEN_CLI_OPTS} test ${MVN_REPOSITORY}"

maven-package:
  stage: package
  needs:
    - maven-test
  script: "mvn ${MAVEN_CLI_OPTS} package ${MVN_REPOSITORY}"
  artifacts:
    paths:
      - target/taskify-1.0.0.jar

docker-build:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  needs:
    - maven-package
  script:
    - docker build -t cjrcordeiro/taskify:1.0.0 .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push cjrcordeiro/taskify:1.0.0

execute-deploy:
  stage: deploy
  only:
    - main
  tags:
    - gcp-taskify-api
  needs:
    - docker-build
  script:
    - docker run -dti --env-file env_db.txt --name taskify -p 8080:8080 cjrcordeiro/taskify:1.0.0