image: maven:3.8.1-openjdk-17

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"
  MVN_REPOSITORY: "-Dmaven.repo.local=.m2/repository"

stages:
  - build
  - test
#   - package
#   - deploy

maven-build:
  stage: build
  script: "mvn $MAVEN_CLI_OPTS compile"

unit-tests:
  stage: test
  script: "mvn $MAVEN_CLI_OPTS test $MVN_REPOSITORY"