image: maven:3.9.6-amazoncorretto-17

cache:
  paths:
    - .m2/repository

# variables:
#   MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"

stages:
  - build
  - test
#   - package
#   - deploy

maven-build:
  stage: build
  script: "mvn compile"

unit-tests:
  stage: test
  script: "mvn install"