image: maven:3.9.6-amazoncorretto-17
variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"
stages:
  - build
  - test
#   - package
#   - deploy

maven-build:
  stage: build
  script: "mvn $MAVEN_CLI_OPTS compile"

unit-tests:
  stage: test
  script: "mvn $MAVEN_CLI_OPTS test"